export const site = {
 name: 'BrandsThink',
 origin: 'https://brandsthink-growth.muhammedanasmr1.chatgpt.site',
 description: 'BrandsThink connects growth strategy, performance marketing, search, content, AI and automation for businesses in Trivandrum, Calicut and Kochi.',
 phones: ['+91 9633033322', '+91 7012380072'],
 whatsapp: '919633033322',
 email: '',
 award: 'Best Creative Advertising Leader 2026',
 metrics: [['100+', 'Clients'], ['400+', 'Projects'], ['5+', 'Years of experience'], ['3+', 'SaaS products']],
 presence: ['Trivandrum', 'Calicut'], channels: ['Kochi', 'UAE', 'UK'],
};
export type Service = {slug:string;name:string;short:string;answer:string;deliverables:string[];measure:string;group:string};
export const services:Service[] = [
 {slug:'growth-marketing',name:'Growth marketing',group:'Strategy',short:'One strategy. Every stage of the customer journey.',answer:'Growth marketing is a continuous process of acquiring, converting and retaining customers through focused experiments. BrandsThink connects your positioning, channels and sales process around a shared business goal.',deliverables:['Customer journey and opportunity mapping','Prioritised experimentation roadmap','Acquisition, conversion and retention planning','Measurement plan and regular learning reviews'],measure:'Qualified opportunities, conversion rates, acquisition cost and retention.'},
 {slug:'performance-marketing',name:'Performance marketing',group:'Acquisition',short:'Campaigns built around customers, not just clicks.',answer:'Performance marketing connects paid media investment to measurable actions. We plan Google and Meta campaigns around the offer, audience and conversion path, then use evidence to decide what deserves more budget.',deliverables:['Audience, offer and campaign strategy','Google Ads and Meta Ads campaign management','Creative testing and landing-page alignment','Conversion tracking and lead-quality feedback'],measure:'Cost per qualified lead, customer acquisition cost and attributable sales where reliable tracking is available.'},
 {slug:'seo',name:'SEO, GEO & AEO',group:'Discovery',short:'Be discoverable. Be useful. Be worth citing.',answer:'SEO improves search discoverability. GEO and AEO describe work that helps information be understood and retrieved in generative and answer-led experiences. We build useful content, accessible websites and clear business information; inclusion in any search or AI answer is never guaranteed.',deliverables:['Technical and on-page SEO review','Search intent and topic-cluster planning','Answer-first service content and appropriate structured data','Local discovery and consistent business information'],measure:'Relevant organic enquiries, search visibility, indexed content and qualified visits.'},
 {slug:'personal-branding',name:'Personal branding',group:'Authority',short:'Turn your expertise into a recognisable point of view.',answer:'Personal branding helps founders and professionals communicate what they know, who they help and why their perspective matters. BrandsThink builds a consistent narrative and publishing system around your real expertise.',deliverables:['Positioning and founder narrative','Editorial pillars and content calendar','LinkedIn and social content direction','Video concepts and thought-leadership formats'],measure:'Relevant conversations, audience quality, profile discovery and inbound opportunities.'},
 {slug:'ai-marketing',name:'AI marketing',group:'Intelligence',short:'Practical intelligence. Human creative judgement.',answer:'AI marketing uses AI-assisted workflows to support research, content and operations. BrandsThink starts with a business use case, sets human review points and evaluates output quality before scaling a workflow.',deliverables:['AI workflow and use-case discovery','Assisted content production systems','Prompt and brand-context frameworks','Human review, quality and handoff processes'],measure:'Production time, revision effort, brand consistency and the business outcome of each workflow.'},
 {slug:'ai-anchor-videos',name:'AI anchor videos',group:'Content',short:'A repeatable presenter format for your message.',answer:'AI anchor videos use a synthetic presenter to deliver an approved script. They can support explainers and recurring updates, with clear disclosure, appropriate rights and human approval of the final message.',deliverables:['Script and presentation concept','Presenter and voice direction with appropriate permission','Branded visual templates and captions','Final content and disclosure review'],measure:'Completion rates, message comprehension and relevant enquiries, with no invented audience response.'},
 {slug:'marketing-automation',name:'Marketing automation',group:'Systems',short:'Make the next step happen at the right time.',answer:'Marketing automation connects customer signals to useful follow-up. We map lead routing, nurturing and sales handoffs so that each enquiry has a clear owner and next action.',deliverables:['Lead journey and workflow mapping','Triggered nurture and follow-up design','Sales handoff and notification rules','Reporting, exception handling and team training'],measure:'Response time, handoff completion, lead progression and recovered opportunities.'},
 {slug:'whatsapp-automation',name:'WhatsApp automation',group:'Systems',short:'Better conversations. Fewer missed enquiries.',answer:'WhatsApp automation helps a business manage consent-based conversations and follow-up. BrandsThink designs enquiry flows, qualification and human handoffs around your customer journey and the requirements of your chosen provider.',deliverables:['Opt-in and conversation flow design','Enquiry qualification and routing','CRM handoff and follow-up workflows','Human support escalation and reporting'],measure:'Response time, qualified conversations, opt-outs and lead-to-appointment progression.'},
 {slug:'crm-erp',name:'CRM & ERP systems',group:'Technology',short:'Connect the marketing promise to the sales process.',answer:'CRM organises customer relationships; ERP connects operational processes. BrandsThink helps define the information, stages and integrations needed to connect marketing, sales and business operations.',deliverables:['Process discovery and requirements mapping','Pipeline stages, ownership and data design','Integration and migration planning','Team onboarding and operational reporting'],measure:'Data completeness, follow-up adherence, process time and pipeline visibility.'},
 {slug:'branding',name:'Branding',group:'Identity',short:'A clear position. An unmistakable identity.',answer:'Branding makes your business easier to recognise, understand and remember. We connect positioning and messaging with a visual identity that works consistently across customer touchpoints.',deliverables:['Brand discovery and positioning','Verbal identity and messaging system','Visual identity and application design','Practical brand guidelines'],measure:'Message clarity, consistency and customer understanding.'},
 {slug:'social-content-marketing',name:'Social & content',group:'Creative',short:'Ideas with a role in the bigger growth picture.',answer:'Social and content marketing build attention and trust through useful, relevant communication. BrandsThink creates editorial systems that connect brand storytelling with customer questions and business priorities.',deliverables:['Content pillars and channel strategy','Campaign concepts and editorial planning','Social creative, copy and video direction','Publishing workflow and learning reviews'],measure:'Meaningful engagement, qualified traffic, enquiries and content-assisted conversions.'},
 {slug:'web-development',name:'Web development',group:'Experience',short:'Fast, clear websites that turn interest into action.',answer:'A growth-focused website explains the offer, answers buying questions and makes the next step easy. BrandsThink connects responsive design, accessible content, technical SEO and conversion paths.',deliverables:['Information architecture and conversion planning','Responsive interface design and development','Performance, accessibility and search foundations','Lead capture and integration planning'],measure:'Enquiry completion, Core Web Vitals, usability and qualified organic traffic.'},
 {slug:'lead-generation',name:'Lead generation',group:'Acquisition',short:'Create a path from interest to a qualified opportunity.',answer:'Lead generation attracts prospective customers and captures their interest. We align offers, campaigns, landing pages and follow-up around what makes a lead genuinely useful to your sales team.',deliverables:['Ideal customer and qualification criteria','Offer and landing-page strategy','Paid and organic acquisition planning','CRM routing and sales feedback loops'],measure:'Qualified leads, appointment rates, opportunity value and acquisition cost.'},
];
export const faqs = [
 ['What does a growth marketing company do?','A growth marketing company connects acquisition, conversion and retention through strategy, content, campaigns and ongoing experiments. BrandsThink also connects AI and automation to the sales journey.'],
 ['Does BrandsThink work in Trivandrum, Calicut and Kochi?','BrandsThink has a presence in Trivandrum and Calicut, with marketing channels in Kochi, UAE and UK. We work with Kochi businesses through that network; we do not list a Kochi office address.'],
 ['How much does a growth marketing engagement cost?','Scope depends on your goals, channels, content needs and existing systems. Share your business brief to discuss an appropriate scope. Advertising spend and third-party software should be agreed separately.'],
 ['How soon can we expect results?','Timing depends on your starting point, offer, budget, channel and sales cycle. Early work establishes measurement and tests assumptions. Organic visibility and retention need sustained work; there is no guaranteed timeline or ranking.'],
 ['Can you connect marketing to WhatsApp and our CRM?','Yes. BrandsThink offers WhatsApp automation, marketing automation and CRM/ERP services. The integration scope depends on your provider, access, customer consent and existing sales process.'],
 ['What happens when I request an AI Growth Audit?','You share your business context, goals and challenges. Your request is securely recorded for BrandsThink to review. This form does not scan your website or generate an automated score. You can also continue the conversation on WhatsApp.'],
];
export const stages=[
 ['Strategy','Find the real constraint.','Clarify your customer, offer and goals. Set a baseline before choosing channels.','growth-marketing'],
 ['Acquisition','Attract the right attention.','Connect search, paid media and content to a relevant customer need.','performance-marketing'],
 ['Conversion','Make interest actionable.','Align the landing page, offer and follow-up to remove friction.','web-development'],
 ['Automation','Keep opportunities moving.','Route enquiries, nurture interest and give sales a clear next step.','marketing-automation'],
 ['Retention','Earn the next purchase.','Build useful communication beyond the first sale and learn from customers.','social-content-marketing'],
 ['Scale','Grow what earns it.','Use evidence from experiments to decide what to improve, stop or expand.','growth-marketing'],
];
export const industries=[
 {slug:'real-estate',name:'Real estate & construction',need:'From project interest to a qualified site visit.',approach:'Connect location-led creative, useful project information and enquiry qualification. Route each lead to a sales owner and track site visits separately from raw enquiries.',focus:['Project discovery','Site-visit enquiries','Sales follow-up']},
 {slug:'healthcare',name:'Healthcare',need:'Build trust before the first appointment.',approach:'Make service information clear, support local discovery and simplify appointment enquiries. Content should be reviewed by an appropriate professional and avoid misleading treatment or outcome claims.',focus:['Local discovery','Patient information','Appointment journeys']},
 {slug:'education',name:'Education',need:'Help the right learner make an informed choice.',approach:'Organise course information around fit, requirements and learning goals. Connect enquiries to counsellors and track progression from interest to application without promising admissions or employment outcomes.',focus:['Course discovery','Counselling enquiries','Application follow-up']},
 {slug:'solar',name:'Solar & energy',need:'Turn technical questions into informed enquiries.',approach:'Use clear explainers, suitability questions and transparent proposal journeys. Help sales understand the prospect’s needs before a consultation; support savings claims with project-specific evidence.',focus:['Customer education','Lead qualification','Consultation handoff']},
 {slug:'hospitality',name:'Hospitality',need:'Make the next stay easier to discover and book.',approach:'Connect destination and property storytelling with clear offers and direct enquiry paths. Measure booking intent and enquiry quality, and plan useful communication for returning guests.',focus:['Destination content','Direct enquiries','Guest retention']},
 {slug:'ecommerce',name:'Retail & ecommerce',need:'Connect product discovery to repeat purchase.',approach:'Align product positioning, paid creative and store experience. Diagnose conversion friction and create permission-based retention journeys before simply increasing acquisition spend.',focus:['Product discovery','Store conversion','Repeat purchases']},
 {slug:'b2b',name:'B2B & technology',need:'Build confidence across a longer buying journey.',approach:'Combine founder expertise, useful service content and lead nurturing. Define qualified opportunities with sales and use CRM stages to distinguish interest from buying intent.',focus:['Founder authority','Demand generation','Pipeline nurturing']},
];
export const locations=[
 {slug:'growth-marketing-calicut',city:'Calicut',kicker:'CALICUT ROOTS. CUSTOMER-FIRST GROWTH.',intro:'BrandsThink is a growth marketing company with a presence in Calicut (Kozhikode). We connect performance marketing, SEO, content and automation to help businesses turn product discovery and service enquiries into useful customer conversations.',heading:'Connect local discovery to repeat business.',body:'For a Calicut business, the journey may start with a product search, a recommendation or a social post and continue through a call, a store visit or WhatsApp. We plan those steps together. Whether you sell locally or serve customers across the wider Malabar region, the brief starts with your actual service area, customer needs and team capacity.',priorities:[['Make your offer easy to find and understand','Build clear product and service pages around customer questions in Calicut and Kozhikode. Choose Malayalam or English content according to your audience, and keep business information consistent.'],['Turn interest into a useful conversation','Connect campaign landing pages to enquiry flows that capture the product, service or appointment a customer needs. Route each conversation to the right person and measure qualified enquiries separately from clicks.'],['Create a reason to come back','Plan useful post-purchase content and permission-based follow-up. For retail and service teams, review repeat enquiries, response time and customer progression before increasing campaign spend.']],faq:[['Does BrandsThink have a presence in Calicut?','Yes. BrandsThink has a stated presence in Calicut and Trivandrum. Call +91 9633033322 or +91 7012380072 to arrange a consultation and confirm the meeting location or online format.'],['Do you work with businesses in Kozhikode as well as Calicut?','Calicut and Kozhikode refer to the same city. This page covers our approach for businesses there; any wider Malabar service area is agreed around your business and delivery capacity.'],['Which marketing services can a Calicut business combine?','An engagement can combine local SEO, performance marketing, social and content marketing, web development, WhatsApp automation and CRM workflows. We select the scope around your offer, sales process and current bottleneck.'],['Can you plan Malayalam and English marketing content?','We can discuss the language mix during planning and agree the content, review process and delivery scope with your team. Language choices should reflect how your customers search, ask questions and make decisions.'],['Can you guarantee a top Google ranking in Calicut?','No. Search rankings are determined by search engines and can change. We focus on useful local content, technical foundations and relevant enquiries, and measure progress against your starting point.']]},
 {slug:'growth-marketing-trivandrum',city:'Trivandrum',kicker:'LOCAL ROOTS. CONNECTED AMBITION.',intro:'BrandsThink is a growth marketing company in Trivandrum connecting strategy, performance marketing, SEO, content, AI and automation. We help businesses build a clearer path from discovery to qualified enquiry and customer retention.',heading:'Build a stronger local growth system.',body:'For a business serving Thiruvananthapuram, visibility is only one part of the journey. Customers also need clear service information, credible answers and a simple way to reach the right person. We connect local discovery to landing pages, enquiry handling and follow-up.',priorities:[['Be found for the right need','Organise service pages around real customer questions and keep your approved business information consistent.'],['Make every enquiry useful','Match offers to your service area, capture relevant context and distinguish a qualified enquiry from an incidental click.'],['Close the follow-up gap','Connect campaigns to WhatsApp or CRM workflows so the team can see ownership, status and the next action.']],faq:[['Is BrandsThink based in Trivandrum?','BrandsThink has a presence in Trivandrum and Calicut. Call us to coordinate a consultation; a street address has not been published on this site.'],['Can you support local service businesses?','Yes. The approach can combine local SEO, service content, paid acquisition and enquiry follow-up, tailored to your service area and customer journey.']]},
 {slug:'growth-marketing-kochi',city:'Kochi',kicker:'CREATIVE THINKING. COMMERCIAL CLARITY.',intro:'Looking for a growth marketing company in Kochi? BrandsThink works with Kochi businesses through its marketing channels, bringing growth strategy, creative, AI, founder branding and automation into a connected plan.',heading:'Give your next growth stage a joined-up plan.',body:'For a Kochi business expanding its reach, a stronger campaign needs a stronger system behind it. We connect distinctive positioning and creative with founder authority, conversion-focused experiences and sales follow-up. The starting point is your market and sales cycle, rather than a fixed channel package.',priorities:[['Build a distinctive market position','Align brand messaging, founder content and campaign creative around a specific customer and buying problem.'],['Connect local demand with wider ambition','Plan separate journeys for local enquiries and wider-market opportunities, with relevant offers and clear measurement.'],['Bring marketing and sales together','Use qualification rules, CRM stages and useful nurture content to support considered purchases and longer sales cycles.']],faq:[['Does BrandsThink have an office in Kochi?','BrandsThink serves Kochi through its marketing channels. Its stated presence is in Trivandrum and Calicut; this website does not claim a physical Kochi office.'],['How can a Kochi team work with BrandsThink?','Start with a discovery conversation and share your goals, existing channels and sales process. We can agree the collaboration format, reporting rhythm and scope around your team.']]},
];
export type CaseStudy={slug:string;client:string;industry:string;challenge:string;approach:string[];results:string;approved:boolean;source:string};
export const caseStudies:CaseStudy[]=[];
export type Testimonial={name:string;role:string;quote:string;approved:boolean;source:string};
export const testimonials:Testimonial[]=[];
export const articles=[
 {slug:'what-is-growth-marketing',title:'Growth is a system. Not a channel.',category:'GROWTH STRATEGY',read:'2 min read',description:'A practical framework for connecting acquisition, conversion and retention.',answer:'Growth marketing is the practice of improving acquisition, conversion and retention through ongoing experiments. It starts with a business constraint and a measurable hypothesis, not a list of channels.',sections:[['Start with the bottleneck','If good enquiries are not turning into conversations, more traffic may only make the problem more expensive. Map the path from first visit to sale, find where people stop and agree what counts as a qualified opportunity.'],['Turn a question into an experiment','A useful hypothesis is specific: simplifying a consultation form may increase completed enquiries without reducing quality. Decide what to change, how to measure it and what evidence will justify keeping it. Avoid changing the offer, audience and landing page all at once when you need to understand the cause.'],['Connect the learning loop','Marketing data alone rarely describes the full journey. Ask sales which enquiries progressed and why others did not. Connect campaign sources to CRM stages where appropriate, and evaluate customer quality alongside acquisition cost.'],['Use a balanced review','Review traffic, qualified enquiries, conversion, acquisition cost and retention together. A campaign can look efficient at the lead stage and still underperform commercially. Set targets from your own baseline and context rather than borrowed benchmarks.']]},
 {slug:'seo-geo-aeo',title:'Search has changed. Clarity still wins.',category:'SEARCH & AI',read:'2 min read',description:'What SEO, GEO and AEO mean for a useful, discoverable business website.',answer:'SEO, GEO and AEO share a practical foundation: make accurate, useful information easy to discover and understand. Different discovery experiences do not remove the need for good content and an accessible website.',sections:[['Explain the business clearly','Put the service, customer problem and next step in readable page content. Use descriptive headings and answer important questions directly before adding detail. Make the organisation and its real locations easy to understand.'],['Publish evidence people can inspect','Approved case studies should explain the challenge, work and measurement period. Link claims to supporting evidence where possible. Do not invent statistics, customer quotes or awards to make a page look authoritative.'],['Keep the technical basics strong','Google says its existing SEO practices remain relevant to AI features and that no special AI schema is required. Keep important content available as text, connect useful pages with internal links and make structured data match the visible content.'],['Measure without promising inclusion','Search and AI systems decide what to show. Monitor relevant enquiries and discoverability over time; do not treat an automated visibility score as proof of business growth. No provider can guarantee inclusion in every AI answer.']],source:'https://developers.google.com/search/docs/appearance/ai-features'},
 {slug:'fix-your-lead-follow-up',title:'Your next growth opportunity may be after the click.',category:'AUTOMATION',read:'2 min read',description:'A practical lead follow-up checklist for marketing and sales teams.',answer:'A useful lead follow-up system gives every enquiry an owner, a next action and a visible status. Automation supports that process; it cannot repair an unclear offer or replace a thoughtful conversation.',sections:[['Agree what a good lead looks like','Define the minimum context sales needs: the customer’s need, location where relevant, timing and preferred contact method. Ask only for information you will use, and explain why you need it.'],['Design the handoff before the workflow','Decide who responds, how enquiries are assigned and when a human should take over. Keep an exception path for missing information or an unavailable team member. Test the whole flow with realistic enquiries.'],['Make follow-up useful and permission-based','A reminder should help a customer take the next step. Respect contact preferences and opt-outs. Keep WhatsApp provider requirements, message permissions and customer expectations part of the implementation brief.'],['Review progression, not message volume','Track whether enquiries receive a response and progress to a meaningful conversation. More automated messages are not a growth outcome. Look for stalled stages and update the process with the team that actually uses it.']]},
];


