import {site,services,faqs,articles,caseStudies,testimonials} from '@/content/site';
import {FAQ,CTA,IndustryLinks} from '@/components/site';
import {GrowthEngine,Sunny,AuditForm} from '@/components/experience';
import {PageSchema} from '@/lib/seo';
import {ClientsShowcase} from '@/components/clients';
export default function Home(){const approved=caseStudies.filter(c=>c.approved);return <main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow">INDEPENDENT MINDS. CONNECTED GROWTH.</p><h1>We don’t<br/>chase reach.<br/><span>We engineer<br/>growth.</span></h1><p className="lead">Strategy, creativity and intelligent technology.<br/>One connected engine for your next stage of growth.</p><div className="actions"><a className="button" href="#audit">Build my growth engine ↗</a><a className="text-link" href="#engine">Explore the approach <span>↓</span></a></div><p className="hero-note">TRIVANDRUM + CALICUT / CONNECTED BEYOND BORDERS</p></div><div className="hero-art"><img src="/hero.webp" alt="" width="1536" height="1024" fetchPriority="high"/><span className="art-label label-top">STRATEGY × CREATIVITY × AI</span><span className="art-label label-bottom">THE BRANDSTHINK GROWTH ENGINE / 01</span></div></section><section className="metrics" aria-label="BrandsThink in numbers">{site.metrics.map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</section><section className="award-spotlight" aria-labelledby="award-title"><div className="award-year" aria-hidden="true"><span>✦</span>2026</div><div className="award-copy"><p className="eyebrow">CREATIVE LEADERSHIP / RECOGNITION</p><h2 id="award-title">{site.award}</h2><p>Award-winning creative thinking.<br/>Growth-minded execution.</p><a className="text-link" href="/about/">Meet BrandsThink ↗</a></div></section>
<ClientsShowcase/>
<section id="engine" className="section"><div className="section-heading"><div><p className="eyebrow">01 / THE CONNECTED APPROACH</p><h2>Great marketing connects.<br/><span>Great growth compounds.</span></h2></div><p className="section-aside">More channels don’t always mean more growth. The opportunity is in making them work together.</p></div><GrowthEngine/></section>
<section id="services" className="section"><div className="section-heading"><div><p className="eyebrow">02 / OUR EXPERTISE</p><h2>Many disciplines.<br/>One growth mindset.</h2></div><a className="text-link" href="/services/">Explore all expertise ↗</a></div><div className="service-grid">{services.slice(0,6).map((s,i)=><a className="service-card" href={`/${s.slug}/`} key={s.slug}><div className="card-top"><span>0{i+1} / {s.group}</span><span aria-hidden="true">↗</span></div><h3>{s.name}</h3><p>{s.short}</p></a>)}</div><div className="service-strip">{services.slice(6).map(s=><a key={s.slug} href={`/${s.slug}/`}>{s.name} ↗</a>)}</div></section>
<section className="section proof-section"><div><p className="eyebrow">03 / THE WORK BEHIND THE NUMBERS</p><h2>Growth deserves<br/><span>more than a claim.</span></h2><p className="lead">The brief. The thinking. The work. The outcome.<br/>That’s how we believe a case study should read.</p><a className="text-link" href="/case-studies/">Our case-study approach ↗</a></div><div className="proof-panel"><span className="mini-label">FROM CHALLENGE TO LEARNING</span>{['Define the business challenge','Connect strategy and execution','Measure what actually changed'].map((s,i)=><div className="proof-row" key={s}><span>0{i+1}</span><h3>{s}</h3></div>)}<p>{approved.length?'Explore our approved project stories.':'Discuss relevant work and available evidence with our team.'}</p><a href="/contact/" className="text-link">Request relevant work ↗</a></div></section>
<section className="section industries"><div><p className="eyebrow">04 / BUILT AROUND YOUR BUSINESS</p><h2>Different markets.<br/>Different challenges.<br/><span>Same ambition.</span></h2><p className="lead">An approach shaped by how your customers discover, decide and buy.</p></div><IndustryLinks/></section>
<section id="sunny" className="section sunny-section"><div><p className="eyebrow">05 / A BRIGHTER WAY TO THINK</p><h2>Meet Sunny AI.<br/><span>Your next perspective.</span></h2><p className="lead">BrandsThink’s AI marketing consultant. Explore where your growth system could be stronger.</p><p className="muted">Start with a guided recommendation below, then take the conversation to our team.</p><span className="sunny-mark" aria-hidden="true">✳</span></div><Sunny/></section>
<section className="section voice-section"><p className="eyebrow">06 / TRUST, WITH CONTEXT</p><h2>Real experiences.<br/>In our clients’ own words.</h2>{testimonials.filter(t=>t.approved).length?testimonials.filter(t=>t.approved).map(t=><blockquote key={t.name}><p>{t.quote}</p><cite>{t.name} · {t.role}</cite></blockquote>):<div className="voice-empty"><p>Want a closer look at how we work?<br/>Ask us about relevant projects and available client references.</p><a className="text-link" href="/contact/">Talk to the team ↗</a></div>}</section>
<section id="audit" className="section audit-section"><div><p className="eyebrow">07 / FIND YOUR NEXT OPPORTUNITY</p><h2>Your growth engine.<br/><span>Let’s look under<br/>the hood.</span></h2><p className="lead">Request an AI Growth Audit. Tell us about your business, your goals and what’s getting in the way.</p><ul className="check-list"><li>Search & content opportunities</li><li>Acquisition & conversion gaps</li><li>AI & automation possibilities</li></ul><p className="fine-print">A brief for our team to review. No simulated scan, instant score or guaranteed results.</p></div><AuditForm/></section>
<section className="section"><div className="section-heading"><div><p className="eyebrow">08 / THE THINKING ROOM</p><h2>A little clarity.<br/>A lot of possibility.</h2></div><a className="text-link" href="/insights/">All insights ↗</a></div><div className="article-grid">{articles.map((a,i)=><a className="article-card" href={`/insights/${a.slug}/`} key={a.slug}><div className={'article-cover cover-'+i} aria-hidden="true"><span>{['GROWTH\nIS A SYSTEM.','SEARCH.\nANSWER.\nDISCOVER.','AFTER\nTHE CLICK.'][i]}</span><i>↗</i></div><p className="mini-label">{a.category} · {a.read}</p><h3>{a.title}</h3><p>{a.description}</p></a>)}</div></section>
<section className="section location-section"><p className="eyebrow">09 / KERALA ROOTS. WIDER HORIZONS.</p><h2>Growth marketing company<br/>in Trivandrum, Calicut & Kochi.</h2><p className="lead">BrandsThink connects strategy, performance marketing, SEO, content, AI and automation. With branch presence in Trivandrum and Calicut, our marketing channels extend to Kochi, UAE and UK.</p><div className="location-grid"><a href="/growth-marketing-trivandrum/"><span>01 / OUR PRESENCE</span><h3>Trivandrum ↗</h3><p>Local discovery, qualified enquiries and connected follow-up.</p></a><a href="/growth-marketing-kochi/"><span>02 / OUR MARKETING CHANNEL</span><h3>Kochi ↗</h3><p>Creative, founder visibility and systems for the next stage of growth.</p></a><a href="/growth-marketing-calicut/"><span>03 / CALICUT BRANCH</span><h3>Calicut ↗</h3><p>Product discovery, customer conversations and repeat business in Kozhikode.</p></a></div></section>
<section className="section faq-section"><div><p className="eyebrow">10 / GOOD QUESTIONS</p><h2>Before we<br/>get growing.</h2></div><FAQ items={faqs}/></section><CTA/><PageSchema title="BrandsThink | Growth Marketing in Trivandrum & Kochi" description={site.description} path="/" faq={faqs}/></main>}
