'use strict';
const base='/brandsthink';
const advice=[{title:'Start with fit, not volume.',text:'Define a qualified enquiry with your sales team. Then connect the offer, audience, landing page and follow-up. Review which leads progress before increasing spend.',href:'/lead-generation/'},{title:'Make your expertise easy to find.',text:'Start with the questions your customers ask. Build clear service pages, publish useful answers and keep your real business information consistent across search touchpoints.',href:'/seo/'},{title:'Give every enquiry a next step.',text:'Map who owns each enquiry, how quickly the team can respond and where handoffs stall. Then connect WhatsApp and CRM workflows around that process.',href:'/marketing-automation/'}];
document.querySelectorAll('.prompt-options button').forEach((button,index)=>button.addEventListener('click',()=>{document.querySelectorAll('.prompt-options button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const panel=document.querySelector('.sunny-response');panel.querySelector('h3').textContent=advice[index].title;panel.querySelector('p').textContent=advice[index].text;panel.querySelector('a').href=base+advice[index].href;}));
for(const form of document.querySelectorAll('.audit-form')){
 const button=form.querySelector('button[type="submit"]');button.disabled=false;
 form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));if(data.companyFax)return;const lines=['Hello BrandsThink, I would like to discuss a Growth Audit.'];for(const [key,label] of Object.entries({name:'Name',business:'Business',email:'Email',phone:'Phone',website:'Website',industry:'Industry',budget:'Marketing spend',currentLeads:'Current monthly leads',targetLeads:'Target monthly leads',challenge:'Growth challenge'})){if(data[key])lines.push(`${label}: ${data[key]}`)}let result=form.querySelector('.demo-result');if(!result){result=document.createElement('div');result.className='demo-result';result.setAttribute('role','status');form.append(result)}result.replaceChildren();const text=document.createElement('p');text.textContent='Your message is ready. Nothing has been saved or sent. Open WhatsApp, review the message and choose whether to send it.';const link=document.createElement('a');link.className='button';link.textContent='Review in WhatsApp ↗';link.href='https://wa.me/919633033322?text='+encodeURIComponent(lines.join('\n'));result.append(text,link);result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'});});
 form.addEventListener('input',()=>form.querySelector('.demo-result')?.remove());
}
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.service-card,.article-card,.proof-panel').forEach(e=>observer.observe(e));}
